version: '3.8'

services:
  php:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    container_name: php
    volumes:
      - .:/var/www/html
    ports:
      - "9000:9000"
    networks:
      - laravel

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html
      - ./docker/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - php
    networks:
      - laravel

networks:
  laravel:
    driver: bridge